<?php
    //Hatoon Code
    //Access Token Page
    function token ($length = 10){
        $random_string = '';
        $characters = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
        $characters_length = strlen($characters);
        for($i = 0 ; $i < $length ; $i++){
            $random_string .= $characters[rand(0, $characters_length -1)];
        }
        //I have chosen This methode to hash the token value which has stored in cookies
        //because this function has used [HMAC] [Hashbase Message Authentication Code] To hash the token value
        //using 'sha256' hashing algorithem and CodeIgniter Encryption Keys[0iEYKnS6g0ASedfU211L5aL4zWjUP1FJ]
        //which is generated by https://randomkeygen.com/
        $random_string .= HASH_HMAC('sha256',$random_string,'0iEYKnS6g0ASedfU211L5aL4zWjUP1FJ');
        return $random_string; 
    }
    $token = token();
 
//****************************Login Functionalty************************** */
require 'config.php';
if($_POST){
    $username = $_POST['username'];
    $password = $_POST['password'];
    if(empty($username) || empty($password)){
        echo'<script> alert("الرجاء ملىء جميع الحقول!!")</script>';
    }
    else{
        $username_escape = strip_tags($username);
        $password_escape = strip_tags($password);
        $password_encode = md5($password_escape);
        //to get user id and store it in the cookie
        $select_query = 'SELECT * FROM `customers` WHERE username="'.$username_escape.'"
        AND password="'.$password_encode.'"
        ';
        $select = mysqli_query($conndb,$select_query) 
        or mysqli_error($select);
        if($select){
            //if the user has stored in the database
            while($set_data = mysqli_fetch_row($select)){
                //get the id for the user who has logged in
                $user_id = $set_data[0];
                    //store mobile number
                    $mobile_number = $set_data[1];
                    //store subscription type
                    $subscribe_type =  $set_data[3];
                    //store credit that exist in customer's subscription
                    $credit = $set_data[4];
            }
        }
        else{
            echo'<script> alert(" تسجيل دخول خاطئ!! الرجاء التأكد من إسم المستخدم و كلمة المرور")
            </script>';
        }
      
       
      // store the token and the user id in [authentication] table  
      //if(!isset($_COOKIE['token'])){
        $auth_query = 'INSERT INTO `authentication`(`token`, `user_id`)
        VALUES ("'.$token.'","'.$user_id.'")
       ';
        $autho = mysqli_query($conndb,$auth_query)
        or die(mysqli_error($autho));
        if($autho){
            //set[TOKEN] cookie
            $name = 'token';
            $value = $token;
            $expire = time()+ 60*60*24*7;
            setcookie($name, $value, $expire);

            //set[USER_id] cookie
            $name = 'id';
            $value = $user_id;
            $expire = time()+ 60*60*24*7;
            setcookie($name, $value, $expire);
        }
         //}
        if(isset($_COOKIE['token'])){
        
            //the user already logged in(the [TOKEN] cookie still valid)
            $token_cookie = strip_tags($_COOKIE['token']);
            $id_cookie = strip_tags($_COOKIE['id']);
            //make a connection
            $query =  'SELECT * FROM `authentication` WHERE token="'.$token_cookie.'"
            AND user_id="'.$id_cookie.'"
           ';
            $check = mysqli_query($conndb,$query);
            if($check){
            if(mysqli_num_rows($check) > 0){
                //[TOKEN] cookie exist
                //make a connection to get user
                $get_user_query = '
                SELECT * FROM `customers` WHERE id="'.$id_cookie.'"
                ';
                $get_user = mysqli_query($conndb,$get_user_query);
                if($get_user){
                    //set [USER]cookie
                    $name = 'user';
                    $value = $username_escape;
                    $expire = time()+ 60*60*24*7;
                    setcookie($name, $value, $expire);

                    //set [LOGIN] cookie
                    $name = 'login';
                    $value = 1;
                    $expire = time()+ 60*60*24*7;
                    setcookie($name, $value, $expire);

                    //create cookie that stores the mobile number
                    $name = "mobile_number";
                    $value = $mobile_number;
                    $expire = time()+ 60*60*24*7;
                    setcookie($name, $value, $expire);

                    //set cookie that stores the subscription type
                    $name = "subscribe_type";
                    $value = $subscribe_type;
                    $expire = time()+ 60*60*24*7;
                    setcookie($name, $value, $expire);

                    //set cookie that stores the customer's credit
                    $name = "customer_credit";
                    $value = $credit;
                    $expire = time()+ 60*60*24*7;
                    setcookie($name, $value, $expire);
                
                
                header("Location:/php course/php project/customer_info.php");

                }
               
              
            }
            
            else{
                       //end[TOKEN] cookie not exist[user logged out]
                        $name = 'token';
                        $value = null;
                        $expire = time()- 60*60*24*7;
                        setcookie($name, $value, $expire);
                        //end[USER] cookie
                        $name = 'id';
                        $value = null;
                        $expire = time()- 60*60*24*7;
                        setcookie($name, $value, $expire);
                        
                        //end [LOGIN] cookie
                        $name = 'login';
                        $value = 0;
                        $expire = time()+ 60*60*24*7;
                        setcookie($name, $value, $expire);
                        
                        //end cookie that stores the mobile number
                        $name = "mobile_number";
                        $value = null;
                        $expire = time() - 60*60*24*7;
                        setcookie($name, $value, $expire);

                        //end cookie that stores the subscription type
                        $name = "subscribe_type";
                        $value = null;
                        $expire = time() - 60*60*24*7;
                        setcookie($name, $value, $expire);

                        //end cookie that stores the customer's credit
                        $name = "customer_credit";
                        $value = null;
                        $expire = time() - 60*60*24*7;
                        setcookie($name, $value, $expire);
            }
        }
        }
    }

}

?>

<html dir = "rtl">
    <head>
           <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>  
           <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />  
           <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>  
      </head>  
    </head>
    <body>
        <?php if (($_COOKIE['login'] == 0))
        echo"
        <div class ='container ' style='width : 30%; margin-top : 5%'>
                <form method = 'POST' action = ''>
                    <div class = 'form-group'>
                        <label for = 'username'>إسم المستخدم:</label>
                        <input type ='test' id = 'username' name = 'username' class='form-control'/>
                    </div>
                    <div class = 'form-group'>
                        <label for = 'password'>كلمة المرور:</label>
                        <input type ='password' id = 'password' name = 'password' class='form-control'/>
                    </div>
                    <input type = 'submit' name = 'submit' value ='تسجيل دخول' class='btn btn-primary'/>
                   
                    
                </form>
        </div>  
        ";
       ?>  
    </body>
</html>